[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bluesky_hwproxy"
authors = [{name = "Kyle Sunden", email = "contact@ksunden.space"}]
dynamic = ["version", "description"]
